// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7pBy2LXoBfg29t6KX4ZbUWD_MdjRFXjk',
    appId: '1:540282476649:web:d16ad74f5c58a0705d2af8',
    messagingSenderId: '540282476649',
    projectId: 'flutter-blog-app-c51a9',
    authDomain: 'flutter-blog-app-c51a9.firebaseapp.com',
    storageBucket: 'flutter-blog-app-c51a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnt2rtaadPEKsUzcpSS3xDksszi_CNZ9s',
    appId: '1:540282476649:android:74fa88d21155bd495d2af8',
    messagingSenderId: '540282476649',
    projectId: 'flutter-blog-app-c51a9',
    storageBucket: 'flutter-blog-app-c51a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBsg_9WkwaCiNaAg6kXdVd-2Vdw2Iynkk',
    appId: '1:540282476649:ios:8ee4cfb5741addc55d2af8',
    messagingSenderId: '540282476649',
    projectId: 'flutter-blog-app-c51a9',
    storageBucket: 'flutter-blog-app-c51a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBsg_9WkwaCiNaAg6kXdVd-2Vdw2Iynkk',
    appId: '1:540282476649:ios:8ee4cfb5741addc55d2af8',
    messagingSenderId: '540282476649',
    projectId: 'flutter-blog-app-c51a9',
    storageBucket: 'flutter-blog-app-c51a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseBlogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7pBy2LXoBfg29t6KX4ZbUWD_MdjRFXjk',
    appId: '1:540282476649:web:0222887b4bd61b145d2af8',
    messagingSenderId: '540282476649',
    projectId: 'flutter-blog-app-c51a9',
    authDomain: 'flutter-blog-app-c51a9.firebaseapp.com',
    storageBucket: 'flutter-blog-app-c51a9.firebasestorage.app',
  );

}